### ISSUE TITLE
GM-Commands wiki shows raw markdown table data

### ISSUE THREAD

**Issue by Stoabrogga** [azerothcore/wiki#143]
Something went wrong with PR #141. The file looks ok here:
https://github.com/azerothcore/wiki/blob/ffa3fc44d51690051bd9f704d6c5a94ed0af5d6f/docs/GM-Commands.md

But in the wiki it just shows the raw table data:
http://www.azerothcore.org/wiki/GM-Commands

**Comment by Yehonal** [comment]
Have you tried to put 2 newline from the title and the table?

**Comment by Helias** [comment]
The newline fix the problem:

![immagine](https://user-images.githubusercontent.com/519778/69362539-fd226300-0c8e-11ea-837c-fe7b0056b38f.png)

But remains another one: the number of columns per row.
It is caused by these strings: `on|off` instead of `on/off`, or `1|0` and similar strings, where there is the pipe character `|`, the markdown parser could be confused.

**Comment by Helias** [comment]
Fixed: https://github.com/azerothcore/wiki/pull/145

![immagine](https://user-images.githubusercontent.com/519778/69362826-918cc580-0c8f-11ea-8995-179873fd1196.png)
