### ISSUE TITLE
Refactor tables from HTML to Markdown

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/wiki#247]
We need to refactor tables like I did here:

https://github.com/azerothcore/wiki/pull/223
https://github.com/azerothcore/wiki/pull/227
https://github.com/azerothcore/wiki/pull/248

And probably one or two other PRs

I used this to help me + text manipulation in my text editor:
https://www.tablesgenerator.com/markdown_tables

Note: I thought I had already opened an issue about this but i can't find it

**Comment by steenburgh** [comment]
An easy way to find a table that uses HTML is to search for `<tbody>`
https://github.com/azerothcore/wiki/search?q=%3Ctbody%3E

There are currently 221 files with tables in them, so this issue is going take a *long* time to complete. If we want this to change quickly, perhaps we could suggest that anyone who edits a table also converts it to markdown?

**Comment by steenburgh** [comment]
This HTML to Markdown converter may be useful: 
https://jmalarcon.github.io/markdowntables/

**Comment by pangolp** [comment]
What a great contribution @steenburgh. @BarbzYHOOL Is anyone working on this? Because if not, I'll try to do it myself. But it doesn't make sense if someone was already doing it or there is some pull request about it.

**Comment by pangolp** [comment]
Good information, I found the links very useful.
Thank you. @BarbzYHOOL @steenburgh

**Comment by pangolp** [comment]
Virtually all files were converted. There will be a maximum of 4 files left out of the initial 212. So I close the subject. Thank you all for the information.
