### ISSUE TITLE
internal links broken

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/wiki#4]
There was no "issues/" so I added them

Secondly all internal links are now broken, example: http://www.azerothcore.org/wiki/FAQ

**Comment by Yehonal** [comment]
Can't reproduce issues about internal links, can you give me an example by steps?

**Comment by BarbzYHOOL** [comment]
```
3 - I want this fixed or this feature or this module. How can I proceed?

You can open a bounty and if developers are interested by the job, they might do it. Read this: Bountysource
4 - I have an issue, where can I get help?

Read this carefully: How-to-ask-for-help
```

**Comment by Yehonal** [comment]
Ok i see, i've converted all links of this form during the migration: [[Title|Page]] but these are of form [[Page]] and i missed.

So we need to fix by hand i think. 

So How-to-ask-for-help become -> [How to ask help](How-to-ask-for-help.md)    ...i use to put the .md suffix (even if not requested) because it allows to navigate between documents even with the github website and not only on wiki.

i've updated those links you reported.

**Comment by FrancescoBorzi** [comment]
is this still valid?

**Comment by Yehonal** [comment]
Closed for inactivity
